### ISSUE TITLE
Controller and Compute nnode in one system

### ISSUE THREAD

**Issue by AshaSinghP** [nfvlabs/openvim#2]
Hi,

As the requirement of Openvim says it needs two servers. But can Openvim(controller and Compute node) be installed in single system.
Thanks in advance !!

**Comment by gerardo-garcia** [comment]
The project OpenVIM, as well as OpenMANO, has been contributed to the open source community project Open Source MANO (OSM), hosted by ETSI. Refer to https://osm.etsi.org/wkipub to get up-to-date information.

In the case of openvim, you can find more details here:
https://osm.etsi.org/wikipub/index.php/OpenVIM_installation_(Release_One)

Answering your question, controller and compute nodes must be in separated servers.
